---
- name: Run packer
  hosts: localhost
  connection: local
  gather_facts: no
  
  environment: '{{ packer_env }}'
  
  tasks:
  - name: Display vCenter Name
    debug:
      msg: "vCenter : '{{ lookup('env', 'PKR_VAR_vcenter_cluster') }}'"
  - name: Run packer init
    ansible.builtin.command: /usr/bin/packer init packer/

  - name: Run packer validate
    ansible.builtin.command: /usr/bin/packer validate packer/
    register: command_result
    ignore_errors: True
  - name: Check validation result
    fail:
      msg: result.stdout_lines
    when: command_result.rc != 0 or "The configuration is valid." not in command_result.stdout

  - name: Run packer build
    ansible.builtin.command: /usr/bin/packer build packer/
    register: command_result
    ignore_errors: True
  - name: Check build result
    fail:
      msg: result.stdout_lines
    when: command_result.rc != 0
