---
- name: Run packer
  hosts: localhost
  connection: local
  gather_facts: no

 # Connexion au vCenter definie par le credential ansible :
 # - host = $VMWARE_HOST
 # - username = $VMWARE_USER
 # - password = $VMWARE_PASSWORD
  environment:
    '{{ packer_env }}'
    PKR_VAR_vcenter_server: '{{ lookup("env", "VMWARE_HOST") }}'
    PKR_VAR_vcenter_username: '{{ lookup("env", "VMWARE_USER") }}'
    PKR_VAR_vcenter_password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
  
  tasks:
  - name: Display vCenter Name
    debug:
      msg: "vCenter : '{{ lookup('env', 'PKR_VAR_vcenter_cluster') }}'"
  - name: Run packer init
    ansible.builtin.command: /usr/bin/packer init packer/

  - name: Run packer validate
    ansible.builtin.command: /usr/bin/packer validate packer/
    register: command_result
    ignore_errors: True
  - name: Check validation result
    fail:
      msg: result.stdout_lines
    when: command_result.rc != 0 or "The configuration is valid." not in command_result.stdout

  - name: Run packer build
    ansible.builtin.command: /usr/bin/packer build packer/
    register: command_result
    ignore_errors: True
  - name: Check build result
    fail:
      msg: result.stdout_lines
    when: command_result.rc != 0
