---
- name: Run packer
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Run packer init
    ansible.builtin.command:
      cmd: /usr/bin/packer init packer/
  - name: Run packer validate
    ansible.builtin.command:
      cmd: /usr/bin/packer validate packer/
  - name: Run packer build
    ansible.builtin.command:
      cmd: /usr/bin/packer build packer/
